### ISSUE TITLE
Откатить спрайты наушников

### ISSUE THREAD

**Issue by AshtonFox** [Fluffy-Frontier/FluffySTG#100]
1. Персы с короткими волосами стали похожи на цыган
1.1. Или на пидоров
2. Спрайт наушника слишком большой, играть просто невозможно
3. Добавьте лучше серьги. Почему их внезапно наушник заменяет??
4. В общем откатите, по картинке всё понятно
![изображение](https://github.com/Fluffy-Frontier/FluffySTG/assets/31184078/565bc417-c8c9-4a0e-928c-82a0c32c801f)

**Comment by Iajret** [comment]
о нет, спрайты....

**Comment by AshtonFox** [comment]
В принципе терпимо, это в сетапе оно ещё хуёво выглядит, а в игре просто меньше заметно. НО ТЕМНИМЕНИЕ
