### ISSUE TITLE
Автолат для хермита

### ISSUE THREAD

**Issue by Stekmen3** [Fluffy-Frontier/FluffySTG#1994]
На данный момент весь хермит по геймплею ничем не отличается от пеплоходоков. Он также охотится, строит и ловит рыбу. У него, выходца из технологического общества на просторах Лаваланда и Ледника, нет ничего. Даже Эшволкеры круче из-за своих ритуалов. Предлагаю поставить в убежище Отшельника автолат, чтобы у него было хоть что-то и больше возможностей по геймплею.

**Comment by RaShCat** [comment]
Я прошу прощения. Но почему на английском?

**Comment by Stekmen3** [comment]
потому что я не подумал.

**Comment by Stekmen3** [comment]
и вспомнил где я

**Comment by Stekmen3** [comment]
воообщем, да. Проблема в том, что хермит никак геймплейно не отличается от эшей. У эшей даже круче с их ритуалами, а хермиту от всей жизни нужен хотя бы автолат, иначе он ничем таковым не отличается и не является
