### ISSUE TITLE
Аллергия с помощью скиллчипа

### ISSUE THREAD

**Issue by AnimeSosiska** [Fluffy-Frontier/FluffySTG#4439]
Reporting client version: 515.1636

## Issue Summary

Существует скиллчип Integrated Intuitive Thinking And Judging Skillchip - позволяет просто посмотрев на еду понять какой у неё вкус, а так же получить бафы/дебафы за этот вкус. 
Так же это работает и на квирк с аллергией: ты просто начнёшь умирать, словно откусил кусочек от этой еды, хотя просто посмотрел на неё.
Мне кажется, что аллергия не должна на это реагировать.

## Round ID:
9001

## Testmerges:
- [[TM-ONLY] Проверка кнопки Be Antagonist для Create Antagonist ](https://github.com/Fluffy-Frontier/Fluffy-STG/pull/2083)
- [Xenoarchaeology artifacts.](https://github.com/Fluffy-Frontier/Fluffy-STG/pull/3267)
- [Complete overhaul of lavaland ruins.](https://github.com/Fluffy-Frontier/Fluffy-STG/pull/3749)
- [Donated suit](https://github.com/Fluffy-Frontier/Fluffy-STG/pull/4184)
- [Кастомные задачи](https://github.com/Fluffy-Frontier/Fluffy-STG/pull/3912)
- [Stasis surgery nerf](https://github.com/Fluffy-Frontier/Fluffy-STG/pull/4393)

## Reproduction:

1. Создать персонажа с аллергией, любой.
2. Купить скиллчип "Integrated Intuitive Thinking And Judging Skillchip" в автомате Good Clean Fun, в разделе Skillchips.
3. Вставить его в куклу.
4. Пойти посмотреть на еду, которая вызывает аллергию.
5. Умереть.

**Comment by Maximal08** [comment]
Тебе на апстримы, к ТГ и я не думаю что они будут менять эту особенность

**Comment by Iajret** [comment]
Это фича, в ПРе на этот скилл чип так и было сказано. Подробнее: https://github.com/tgstation/tgstation/pull/79902

>This has all of the effects of tasting food (various moodlets based on quality and food type) and can also trigger food allergies if you have them, however it does not consume the food nor give you any nutritional benefit.
