### ISSUE TITLE
Products ff sec vendor bug

### ISSUE THREAD

**Issue by mogeoko** [Fluffy-Frontier/FluffySTG#5073]
### Client Version:

515.1642

### Issue Summary:

Продукты ФФ (наш модуль) не работает для вендоров сбух, просто не добавляет в него вещи.

### Round ID:

Любой

### Test Merge Information:

https://github.com/Fluffy-Frontier/FluffySTG/pull/4893
https://github.com/Fluffy-Frontier/FluffySTG/pull/4957
https://github.com/Fluffy-Frontier/FluffySTG/pull/4973

### Reproduction Steps:

1. Проверить содержимое вендора сб
2. Удостовериться, что в нем нет модульных вещей

**Comment by FeenieRU** [comment]
Это был проёб модуляра Новы в целом, который давно пофиксили:
https://github.com/Fluffy-Frontier/FluffySTG/pull/5060

Обнови билд.

**Comment by mogeoko** [comment]
> Это был проёб модуляра Новы в целом, который давно пофиксили:
> https://github.com/Fluffy-Frontier/FluffySTG/pull/5060
> 
> Обнови билд. 


На 43 не компилит (вроде), проверял это на ффе

**Comment by mogeoko** [comment]
Раз точно пофикшено у нас, то закрывай

**Comment by FeenieRU** [comment]
> Раз точно пофикшено у нас, то закрывай

Пруфы в дис скину
