### ISSUE TITLE
The mirror bot name sucks

### ISSUE THREAD

**Issue by JohnFulpWillard** [Fluffy-Frontier/FluffySTG#682]
## Testmerges:

None

## Reproduction:

1. Look at the mirror bot name
2. It isn't something funny like "Steals-The-PRs"
3. Be miserable

**Comment by AnywayFarus** [comment]
What specifically do you not like? Is it the essence of the nickname or the length? It’s just not particularly clear why it’s bothering you.

**Comment by Iajret** [comment]
That happens, when you lack any creativity at all. :)
Done, thanks for an actually great suggestion!
